# Generated by Django 4.2.30 on 2026-09-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_procurementrequest_actual_delivery_date_and_more'),
        ('suppliers', '0001_initial'),
        ('inventory', '0003_ingredient_unit_cost_stocktransaction_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_at', models.DateTimeField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_shipments', to='inventory.ingredient')),
                ('procurement_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_shipments', to='procurement.procurementrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_shipments', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['supplier', 'ingredient', 'received_at'], name='inventory_i_supplie_4d5154_idx'), models.Index(fields=['received_at'], name='inventory_i_receive_4cc856_idx')],
            },
        ),
    ]
