# Generated by Django 4.2.30 on 2026-09-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('inventory', '0003_ingredient_unit_cost_stocktransaction_notes_and_more'),
        ('forecasting', '0002_aiprocurementalert_accuracy_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDeliveryPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_delivery_date', models.DateField()),
                ('predicted_cycle_days', models.PositiveIntegerField()),
                ('predicted_window_start', models.DateField()),
                ('predicted_window_end', models.DateField()),
                ('estimated_volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active Window'), ('MISSED', 'Window Missed')], default='UPCOMING', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_predictions', to='inventory.ingredient')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_predictions', to='suppliers.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['predicted_window_start', 'status'], name='forecasting_predict_355921_idx'), models.Index(fields=['confidence_score'], name='forecasting_confide_7a7d50_idx')],
                'unique_together': {('supplier', 'ingredient')},
            },
        ),
    ]
